-- Insert room units batch 2 (Balcony Bliss and Poolside Peeks)
WITH room_type_mapping AS (
  SELECT id, name FROM public.room_types
)
INSERT INTO public.room_units (
  unit_number, unit_name, floor_number, room_type_id, bed_configuration, max_occupancy, notes, status
) VALUES 
-- Balcony Bliss
('201', 'Shergar Vista', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 1}, {"type": "Sofa Cum Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 4, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('202', 'Secretariat Horizon', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 1}, {"type": "Sofa Cum Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 4, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('203', 'Desert Orchid Lookout', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 1}, {"type": "Sofa Cum Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 4, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('204', 'Northern Dancer Terrace', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 1}, {"type": "Sofa Cum Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 4, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('205', 'Barbaro Overlook', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 1}, {"type": "Sofa Cum Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 4, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('206', 'Whirlaway Skyview', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 1}, {"type": "Sofa Cum Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 4, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('207', 'Brigadier Gerard Balcony', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 1}, {"type": "Sofa Cum Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 4, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('208', 'Mill Reef Horizon', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 1}, {"type": "Single Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 4, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('209', 'Galileo Vista', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 1}, {"type": "Sofa Cum Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 4, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('212', 'Alleged Overlook', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 1}, {"type": "Sofa Cum Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 4, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('213', 'Enable Skyview', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 1}, {"type": "Sofa Cum Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 4, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('214', 'Sunday Silence Balcony', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 2}, {"type": "Mattress", "count": 1}]'::jsonb, 5, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('215 A/B', 'Dancing Brave Horizon', 1, (SELECT id FROM room_type_mapping WHERE name = 'Balcony Bliss'), '[{"type": "Double Bed", "count": 2}, {"type": "Roll on Bed", "count": 1}, {"type": "Mattress", "count": 1}]'::jsonb, 6, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
-- Poolside Peeks
('210', 'Nashwan Nook', 1, (SELECT id FROM room_type_mapping WHERE name = 'Poolside Peeks'), '[{"type": "Double Bed", "count": 2}, {"type": "Mattress", "count": 1}]'::jsonb, 5, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('211', 'Affirmed Alcove', 1, (SELECT id FROM room_type_mapping WHERE name = 'Poolside Peeks'), '[{"type": "Double Bed", "count": 2}, {"type": "Mattress", "count": 1}]'::jsonb, 5, 'Located on the first floor with swimming pool view, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('303 A/B', 'Lammtarra Lookout', 2, (SELECT id FROM room_type_mapping WHERE name = 'Poolside Peeks'), '[{"type": "Double Bed", "count": 4}]'::jsonb, 8, 'Located around the activity area, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('304 A/B', 'Sunline Suite', 2, (SELECT id FROM room_type_mapping WHERE name = 'Poolside Peeks'), '[{"type": "Double Bed", "count": 4}]'::jsonb, 8, 'Located around the activity area, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('305', 'Silvano Spot', 2, (SELECT id FROM room_type_mapping WHERE name = 'Poolside Peeks'), '[{"type": "Double Bed", "count": 1}]'::jsonb, 2, 'Located around the activity area, well furnished with double bed, TV, telephone and air conditioner.', 'available'),
('306', 'Fiorente Frame', 2, (SELECT id FROM room_type_mapping WHERE name = 'Poolside Peeks'), '[{"type": "Double Bed", "count": 1}]'::jsonb, 2, 'Located around the activity area, well furnished with double bed, TV, telephone and air conditioner.', 'available');