// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmmogqappdtnwqkvzxih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tbW9ncWFwcGR0bndxa3Z6eGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTU3ODEsImV4cCI6MjA2NzczMTc4MX0.snZc3-2CaQjQ0pAiYLH1uFlgy0iIdTvH75CeW3L2Aos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});